version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@1.1.0

jobs:
  install_lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install required dependencies using requirement.txt
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
      - run:
          name: run lint Docker and app
          command: |
            source devops/bin/activate
            make lint
          no_output_timeout: 25m 

          
  configure:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: login build run docker impage
          command: |
            cat ~/my_password.txt | docker login --username rajpurp --password-stdin
            docker build -t rajpurp/project55:1.0 .
            docker run -d --rm --name myapp -p 8081:8080 rajpurp/project55:1.0
            sleep 10
            docker container ls
            sleep 5
            export URL="http://localhost:8081"
            export output=$(curl -s $URL)
            echo "Output of curl : $output"
            if [[ $output == *"Prakash"* ]]; then
               echo "Success"
              docker stop myapp
            else
              docker stop myapp
              exit 1
            fi
            docker push rajpurp/project55:1.0
      

workflows:
  default:
    jobs:
      - install_lint
      - configure:
          requires:
            - install_lint
