version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  kubernetes: circleci/kubernetes@0.12.0
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  install_lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install required dependencies using requirement.txt
          command: |
            python3 -m venv devops
            source devops/bin/activate
            make install
      - run:
          name: run lint Docker and app
          command: |
            source devops/bin/activate
            make lint
          no_output_timeout: 25m 

workflows:
  default:
    jobs:
      - install_lint
